"""empty message

Revision ID: 613e1c1f1758
Revises: 8cfe266243d5
Create Date: 2025-03-06 11:22:43.150737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613e1c1f1758'
down_revision = '8cfe266243d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
